name: GitHub Actions Setup (by KyryloKilin)

run-name: ${{ github.actor }} triggered GitHub Actions

on:
  pull_request:

env:
  GITHUB_ACTIONS: GITHUB_ACTIONS

jobs:
  github-task-job:
    runs-on: ubuntu-latest

    steps:
      - name: Show env GITHUB_ACTIONS
        run: echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"

      - name: Show branch and repository
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.head_ref }}"

      - name: Show triggering event
      - run: echo "The job was triggered by a ${{ github.event_name }} event"
